Markdown & LaTeX rendering, code blocks w/ syntax highlighting, styled tables, headings, and lists.
adamcohenhillel/ADeus pull request #95
Opened 2024-03-14 01:17 UTC by kaeladair

Added Markdown & LaTeX rendering using Katex, styled tables, lists, and headers, added code blocks with syntax highlighting.

Had to add to main chat prompt to ensure proper delimiters and formatting from gpt-4.

Styling is in globals.css for now, as I am not super familiar with tailwind. Easy/quick fix if it is a problem.

<img width="1440" alt="Screenshot 2024-03-13 at 5 44 51 PM" src="https://github.com/adamcohenhillel/ADeus/assets/77252781/41d3a5f2-571c-4e0a-bc2f-da26c9bb0f8a">
<img width="1440" alt="Screenshot 2024-03-13 at 5 45 43 PM" src="https://github.com/adamcohenhillel/ADeus/assets/77252781/ed0dc675-9a3f-415c-8049-2dfba5a98787">
<img width="1440" alt="Screenshot 2024-03-13 at 5 45 57 PM" src="https://github.com/adamcohenhillel/ADeus/assets/77252781/cb1efcc8-d474-40a9-a661-f0cdb0e2000c">

2024-03-14 17:46 UTC, kaeladair commented on app/src/styles/globals.css
> +/* Styling for headers, text, lists */
Will do

2024-03-14 17:50 UTC, adamcohenhillel commented
Pretty awesome stuff - will merge after resolving @Jacksonmills comments!

2024-03-14 17:50 UTC, adamcohenhillel approved these changes

2024-03-14 19:41 UTC, kaeladair commented on app/src/styles/globals.css
> +/* Styling for headers, text, lists */
Should be better now, header/list styles will only apply to the chatlog.

2024-03-14 21:16 UTC, Jacksonmills commented on app/src/styles/globals.css
> +/* Styling for headers, text, lists */
closer! let me make some changes to show you how to do it all in tailwind

2024-03-15 02:56 UTC, Jacksonmills commented
@kaeladair https://github.com/kaeladair/ADeus/pull/2

I have a PR open on your fork that should clean up everything, however when I ask for math rendering it doesn't give it to me despite me not touching those globals

2024-03-15 03:02 UTC, Jacksonmills requested changes
I put in some changes as a PR on your fork, let me know what you think there, one bug with the math stuff or I just suck at prompting

2024-03-15 03:14 UTC, kaeladair commented
> I put in some changes as a PR on your fork, let me know what you think there, one bug with the math stuff or I just suck at prompting

Looks great! Trying to figure out the bug and will get back to you soon

2024-03-15 03:15 UTC, Jacksonmills commented
> > I put in some changes as a PR on your fork, let me know what you think there, one bug with the math stuff or I just suck at prompting
> 
> Looks great! Trying to figure out the bug and will get back to you soon

yeah I saw your screenshot of the equations so I tried asking for one but no luck

2024-03-15 03:21 UTC, kaeladair commented
> > > I put in some changes as a PR on your fork, let me know what you think there, one bug with the math stuff or I just suck at prompting
> > 
> > 
> > Looks great! Trying to figure out the bug and will get back to you soon
> 
> yeah I saw your screenshot of the equations so I tried asking for one but no luck

Everything is working on my end, with the bug being that the GPT is responding with some markdown headers mixed with LaTeX and is doesn't render properly. Will try to prompt it.

2024-03-15 03:53 UTC, Jacksonmills approved these changes

2024-03-15 11:59 UTC, adamcohenhillel commented
merging!

2024-03-15 11:59 UTC, merged